//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public string oid { get; set; }
        public string pid { get; set; }
        public string email { get; set; }
        public string qunt { get; set; }
        public string date { get; set; }
    }
}
